# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
language: java
install:
  - sudo R CMD javareconf
r:
  - oldrel
  - release
  - devel
os:
  - linux
  - osx
arch:
  - x64
  - x86
cache: packages
