# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel
os:
  - linux
  - osx
osx_image: xcode12.5
arch:
  - x64
  - x86
cache: packages
